language: python

python:
 - 3.6

env:
 - DJANGO=2.1.4

before_install:
 - export DJANGO_SETTINGS_MODULE=BEProjectsWeb.settings

install:
 - pip3 install -r requirements.txt

before_script:
 - cd backend/
 - python3 manage.py makemigrations
 - python3 manage.py migrate

script:
 - cd backend/
 - black --check BEProjectsWeb/
 - black --check BEProjectsApp/
 - python3 manage.py test
